# This is a basic workflow to help you get started with Actions

name: Refresh from Home Assistant

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Get latest Home Assistant release tag
        run: |
          git clone https://github.com/home-assistant/core.git ${{ runner.temp }}/core
          export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          git checkout tags/$TAG
          echo "HA_VERSION=$TAG" >> $GITHUB_ENV
          
      - name: Print HA version
        run: echo ${{ GITHUB_ENV.HA_VERSION }}

